package model;

public enum Categories {
    SPORTING_GOODS, BOOKS, COLLECTIBLES, TOYS_AND_GAMES, KITCHEN_AND_HOME, STORAGE_AND_CONTAINERS,
    ELECTRONICS_AND_COMPUTERS, CLOTHES, FURNITURE, OUTDOOR_AND_GARDEN, OTHER
}
